### PR TITLE
Replaced `Mob` with `LivingEntity` in shape abilities

### PR DESCRIPTION
**Pull request by shap-po**
This pull request would allow other mods to use these abilities regardless of the player's shape.

### CODE REVIEW

**Review by ToCraft — APPROVED** [review]

**Comment by ToCraft** [comment]
Do you already have some mod in mind that could use the ShapeAbilities? Maybe we can improve the API further.

**Comment by shap-po** [comment]
Thanks for the quick response and for merging the changes!

I am currently developing [Shappoli](https://modrinth.com/mod/shappoli), an `Origins` addon, part of which integrates with your mod. I made an `execute_shape_ability` action that makes use of those abilities, here is an example: [ExplosionShapeAbility](https://github.com/shap-po/shappoli/blob/feat/1.20.4/shape_abilities/src/main/java/com/github/shap_po/shappoli/integration/walkers/power/factory/ability/ExplosionShapeAbility.java).

It would be great to make the `ID` field required not only for `GenericShapeAbility` but for all `ShapeAbility`, this would allow data-driven systems like `Origins` to check if an entity has a specific ability.

Also, it would be nice to allow mods to easily subscribe to the `ability.onUse()` method with `Mixins` either by making it empty in `ShapeAbility` and all child classes calling `super()` on it or moving [this](https://github.com/ToCraft/woodwalkers-mod/blob/9d6f9d97a2509b6afbd03ab069451912e76b781f/common/src/main/java/tocraft/walkers/network/ServerNetworking.java#L42-L54) part of the networking code to some utility method.

**Comment by shap-po** [comment]
You can safely reject the [make ShapeAbilities call super.onUse()](https://github.com/ToCraft/woodwalkers-mod/pull/140/commits/79077f7df58057ef59b72a49837eb5456176bc68) commit if you don't like it as I am not sure if I like it myself

**Review by ToCraft — CHANGES_REQUESTED** [review]
What about a custom Event that is called when an Ability is used? This way you wouldn't have to use Mixins as they aren't as safe as a direct call is.
Moreover, walkers already introduces some custom events, so it would be sensible.
If you need references on what I mean with a custom Event, you can take a look at the [ShapeEvents](https://github.com/ToCraft/woodwalkers-mod/blob/main/common/src/main/java/tocraft/walkers/api/events/ShapeEvents.java#L12) class and it's [implementations](https://github.com/ToCraft/woodwalkers-mod/blob/main/common/src/main/java/tocraft/walkers/api/PlayerShapeChanger.java#L14) or at the [wiki entry for Events](https://tocraft.dev/docs/craftedcore/Events) I wrote.

**Comment by shap-po** [comment]
I didn't know you had an event system like that, I think I can remove most mixins from my code thanks to it! 🤔

**Comment by shap-po** [comment]
I think this should do it

**Review by ToCraft — APPROVED** [review]

**Comment by shap-po** [comment]
Thanks, I'll look into it! Not sure if I want to globally disable some of the mod features though. I'll make sure to open a new pull request if I add anything useful :>
My MC username is `Shap_po`

**Comment by ToCraft** [comment]
I've added you :D

**Pull request merged**
